# Site settings
title: UW ChemE 512 Methods of Engineering Analysis
email: ccurtis7 -- AT -- uw.edu
description: "Applications of mathematics to problems in chemical engineering; vector calculus; properties and methods of solution of first and second order partial differential equations; similarity transforms, separation of variables, LaPlace and Fourier transforms."
url: "http://uw-cheme512.github.io"
twitter_username: derchadmeister
github_username:  uw-cheme512


# Build settings
markdown: kramdown
