# Site settings
title: UW ChemE 485 Process Design I
email: ccurtis7 -- AT -- uw.edu
description: "Applied economics in chemical engineering design and operations; measures of profitability; capital and operating cost estimates; introduction to design and design strategies."
url: "http://uw-cheme485.github.io"
twitter_username: derchadmeister
github_username:  uw-cheme485


# Build settings
markdown: kramdown
